# Generated by Django 4.2.27 on 2025-12-23 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('period', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('semester', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('QR', 'QR'), ('BT', 'Bluetooth'), ('WIFI', 'WiFi'), ('FACE', 'Face')], default='QR', max_length=20)),
                ('present', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timetableentry')),
            ],
            options={
                'unique_together': {('student', 'timetable_entry', 'date')},
            },
        ),
    ]
